# Parameters of the camera used to record the video which is passed in:
CAMERA_FOCAL_LENGTH: 2.87  # mm, focal length of camera lens
CAMERA_FOCAL_LENGTH_STD: 32  # mm, 35mm equiv. focal length of camera lens
CAMERA_NATIVE_ASPECT: [3, 4]  # Native aspect ratio of camera sensor
CAMERA_VIDEO_ASPECT: [9, 16]  # Aspect ratio of video recorded by camera

# Start and end frames of the video to apply hand detection, and thus tremor
# amplitude measurement, to:
START_FRAME: 1
END_FRAME: 900

# Show GUI when tracking hands?
GUI_HAND_TRACKING: False

# Auto mode runs the program without any user prompting, by taking command line
# inputs. It also stores the results into a csv file.
AUTO_MODE: True
